### ISSUE TITLE
Name conflict of project

### ISSUE THREAD

**Issue by jaredthirsk** [fluent-cms/fluent-cms#3]
I was looking at CMS's for .NET and noticed there are two projects with almost the same name:

- fluent-cms (this one)
- fluentcms  (https://github.com/fluentcms/FluentCMS, https://fluentcms.com/)

Any thoughts about changing your project name to avoid confusion?

**Comment by fluent-cms** [comment]
thanks for letting me know. the link fluent-cms was referenced in a lot of places, I will try to make it clear
